# Generated by Django 6.0.6 on 2026-06-08 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="custom_form_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of objects defining custom questions, e.g. [{'type': 'text', 'question': 'T-Shirt Size?', 'required': true}]",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="payment_details",
            field=models.CharField(
                blank=True,
                help_text="UPI ID or Payment Link",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_price",
            field=models.IntegerField(
                default=0, help_text="Amount in INR. 0 for free events."
            ),
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("applicant_name", models.CharField(max_length=255)),
                ("applicant_email", models.EmailField(max_length=254)),
                ("applicant_phone", models.CharField(max_length=20)),
                ("custom_answers", models.JSONField(blank=True, default=dict)),
                (
                    "payment_screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="payment_screenshots/"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="api.event",
                    ),
                ),
            ],
        ),
    ]
